services:
  app:
    build: . 
    ports:
      - 3001:3001
      - 3002:3000
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgress://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db
      - kafka
  db:
      image: postgres
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 3
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=mydatabase
      volumes:
        - db-data:/var/lib/postgresql/data
  kafka:
    image: apache/kafka:3.7.1
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db-data:
